name: CI Pipeline

on:
  push:
    branches: [ main, dev, dev_pom ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        HEADLESS=true pytest tests/ --html=report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
